struct ThisPacket {} // ...
struct ThatPacket {} // ...

#[register_packet(0)]
fn handle_this(packet: ThisPacket) -> Result<(), MyError> {
    // ...process packet...
    Ok(())
}

#[register_packet(1)]
fn handle_that(packet: ThatPacket) -> Result<(), MyError> {
    // ...process packet...
    Ok(())
}

// --- CODE FROM HERE ON AUTOMATICALLY GENERATED BY MACRO --- //

fn handle(id: i32, data: &[u8]) -> Result<(), MyError> {
    match id {
        0 => handle_this(parse_packet<ThisPacket>(data)?),
        1 => handle_that(parse_packet<ThatPacket>(data)?),
        _ => Ok(())
    }
}